"""Init migration

Revision ID: 3f294bfb2e3f
Revises: 
Create Date: 2024-08-23 14:36:50.871488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import CreateSequence, Sequence


# revision identifiers, used by Alembic.
revision: str = '3f294bfb2e3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence("seq_item_id")))

    op.create_table('item',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('seq_item_id')"), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
